### ISSUE TITLE
Feature req! Can we preload the assembler window with KIM-1 constants  

### ISSUE THREAD

**Issue by lucacr** [maksimKorzh/KIM-1#1]

**Comment by lucacr** [comment]
Hi Code Monkey King, i absolutely love your emulator... but I suck at js (heck, I’m sure you can tell by the fact that I’m intrigued by 6502 assembly...)

I was wondering, why not populate the assembler window with some useful define’s, like SCANDS, PADD, etc.

I see you basically have the KIM-1 ROM as comments in file KIM-1.js

```
/* 1800 */                     //  #define SAD      $1740     ; 6530 A DATA
/* 1800 */                     //  #define PADD     $1741     ; 6530 A DATA DIRECTION
/* 1800 */                     //  #define SBD      $1742     ; 6530 B DATA
/* 1800 */                     //  #define PBDD     $1743     ; 6530 B DATA DIRECTION
```
etc.

Thank you for a very entertaining piece of software! I also love the mobile version

**Comment by maksimKorzh** [comment]
Hello)

Usually the constants are defined in the top of the program, you can do the following thing:

define SCANDS $1F1F
define POINTH $FB
define POINTL $FA
define INH $F9
define SOME_VAR $45

DISPLAY:
  LDA #SOME_VAR
  STA POINTH
  STA POINTL
  STA INH
  JSR SCANDS
  JMP DISPLAY

You can define your own list and use it along with your programs.
The reason why I didn't include it out of the box is to keep things manual
because this project is ultimately done for developing an understanding.

Does this resolve your issue?

**Comment by lucacr** [comment]
Hi Maksim, ok I understand your desire to keep things manual. Looks like I better learn some javascript and fork the program. Thank you for making it available!

**Comment by maksimKorzh** [comment]
Cool) I've added TTY mode support to the emulator today btw. Please make sure to clear browser cache to make it work properly:
https://maksimkorzh.github.io/KIM-1/
see little checkbox 'Serial mode' above KIM logo

**Comment by maksimKorzh** [comment]
If you have issues with pre-loading KIM locations let me know, I'll do it for you personally.

**Comment by lucacr** [comment]
Love it! Thanks! No, no issues at all. I was just going through the code and noticed you basically have the KIM-1 ROM disassembled in the comments. And you have the very same codes in the upper right text area. Maybe do just ONE text area, with all the defines? Just a thought.

Also love your mobile version. I was going through the code and I saw how you preload the program i.e. KIM-venture or MicroChess i.e.
`
      // KIM Venture is preloaded

      dump_ram = '132,239,160,0,169,127,141,...etc.'.split(',');
      dump_riot = '0,0,0,0,0,0,0,0,0,0,...etc.'.split(',');
      for (let i = 0; i < RAM.length; i++) RAM[i] = dump_ram[i];
      for (let i = 0; i < RIOT.length; i++) RIOT[i] = dump_riot[i];
`

so I guess I could do the same if I want to try a new program on the mobile version. Or maybe try and write some kind of "tape" function where you paste hex digits and they go into RAM or RIOT RAM.

**Comment by maksimKorzh** [comment]
Ummm... first thing first.
KIM Venture and my own 6502 chess are preloaded, not MicroChess.
6502 chess: https://github.com/maksimKorzh/6502-chess

The code you've mentioned indeed may be used to preload program into RAM.
Emulator has a converter tool, see 'convert' button - it can generate KIM-1 paper tape format from pasted HEX dump.
It can also convert existing paper tape to so called dcb dump that can then be assembled in the emulator and run.

Finally the matter of having preloaded constants like SCANDS:
1. Simplest way is to paste them into text area that is later converted into code mirror editor instance
2. Intercept 'assemble'  button call and append definition list before the code - it would then get assembled already knowing about definitions.

**Comment by lucacr** [comment]
Wow, I never knew there was a recent chess for the KIM-1! I'm impressed
Also, thanks for the tip re: intercepting the assemble call and injecting the define's.
Ciao from Italia

L.

**Comment by maksimKorzh** [comment]
Thank you) I made it a couple of days ago)
Here's the development progress and explanation of how it works if you're interested:
https://www.youtube.com/watch?v=POTjQXYuv7I&list=PLmN0neTso3JwdHRU2W4sit0xOK7P-LRMS
